language: "node_js"
services:
  - postgresql
node_js:
  - "9.6.1"
before_script:
  - npm install
  - npm run db-create
  - npm run db-migrate
script: DATABASE_URL=postgres://postgres@127.0.0.1:5432/store_manager_db npm test
after_success:
  - npm run coveralls
